@startuml

actor "利用者" as user
participant "バクスター" as bax
participant "わたがし製造機" as machine
database "砂糖置き場" as suger
database "割り箸置き場" as wari

' note over user, wari
note left user
    <要検討事項>
    * ロボットは初期状態で割り箸を持っておく？
    * 砂糖の投入方法？
    * 箸の回収方法？
    * ユーザからのロボットへの指示方法？
    * カメラのレンズ拭いたりする？
end note

user --> bax : 作成依頼（音声？操作？）
suger --> bax : 砂糖を回収
activate bax
bax --> machine : 砂糖投入

group "検討中: わたがし作成中の動作"
bax --> machine : 回転開始
activate machine
bax --> machine : わたあめ製造を開始
bax --> machine : 割り箸を挿入
bax --> machine : 割り箸を回転
bax --> machine : 割り箸を回収
bax --> machine : わたがし製造機を止める
deactivate machine
end

bax --> user : わたあめを渡す
bax <--> wari : 新しい割り箸を把持
bax --> bax : 初期状態に復帰
deactivate bax

@enduml
