@startuml

' actor 利用者 as user


' 利用者 as user

' バクスター as bax
' わたあめ製造機 as machine
' 割り箸置き場 as wari
bax <--> "割り箸置き場" as wari : 新しい割り箸を把持

"利用者" as user --> "バクスター" as bax : 作成依頼（音声？）
activate bax
bax --> "わたがし製造機" as machine : 砂糖投入
bax --> machine : 回転開始
activate machine
bax --> machine : わたあめ製造を開始
bax --> machine : 割り箸を挿入
bax --> machine : 割り箸を回転
bax --> machine : 割り箸を回収
bax --> machine : わたがし製造機を止める
deactivate machine
bax --> user : わたあめを渡す
bax --> bax : 初期状態に復帰
deactivate bax
bax <--> "割り箸置き場" as wari : 新しい割り箸を把持








@enduml
