@startuml

actor "ユーザ" as user
box "Baxter"
participant "Baxter系" as bax
' entity "左腕" as bax_L
' entity "右腕" as bax_R
end box
participant "わたがし製造機" as machine
database "砂糖置き場" as suger
database "割り箸置き場" as wari

' note over user, wari
note left user
    <要検討事項>
    * 割り箸
        * 割り箸を掴むタイミング
        * 置き場側に工夫はいらないか
    * 砂糖
        * 砂糖の投入方法
        * 置き場側に工夫はいらないか
        * 砂糖を補充するタイミング
    * ユーザからのロボットへの指示方法
    * カメラのレンズ汚れないか
end note

user --> bax : 作成依頼
activate bax
suger --> bax : 砂糖を回収
bax --> machine : 砂糖投入

group "検討中: わたがし作成中の動作"
bax --> machine : わたがし機スイッチオン
activate machine
bax --> machine : 割り箸を挿入
bax --> machine : 割り箸を回転
bax --> machine : 割り箸を取り出す
bax --> machine : わたがし製造機を止める
deactivate machine
end

bax --> user : わたあめを渡す
bax <--> wari : 新しい割り箸を把持
bax --> bax : 初期状態に復帰
deactivate bax

@enduml
